// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repo

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIOTPRepo creates a new instance of MockIOTPRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIOTPRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIOTPRepo {
	mock := &MockIOTPRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIOTPRepo is an autogenerated mock type for the IOTPRepo type
type MockIOTPRepo struct {
	mock.Mock
}

type MockIOTPRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIOTPRepo) EXPECT() *MockIOTPRepo_Expecter {
	return &MockIOTPRepo_Expecter{mock: &_m.Mock}
}

// DeleteOTP provides a mock function for the type MockIOTPRepo
func (_mock *MockIOTPRepo) DeleteOTP(context1 context.Context, s string) error {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOTP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIOTPRepo_DeleteOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOTP'
type MockIOTPRepo_DeleteOTP_Call struct {
	*mock.Call
}

// DeleteOTP is a helper method to define mock.On call
//   - context1
//   - s
func (_e *MockIOTPRepo_Expecter) DeleteOTP(context1 interface{}, s interface{}) *MockIOTPRepo_DeleteOTP_Call {
	return &MockIOTPRepo_DeleteOTP_Call{Call: _e.mock.On("DeleteOTP", context1, s)}
}

func (_c *MockIOTPRepo_DeleteOTP_Call) Run(run func(context1 context.Context, s string)) *MockIOTPRepo_DeleteOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIOTPRepo_DeleteOTP_Call) Return(err error) *MockIOTPRepo_DeleteOTP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIOTPRepo_DeleteOTP_Call) RunAndReturn(run func(context1 context.Context, s string) error) *MockIOTPRepo_DeleteOTP_Call {
	_c.Call.Return(run)
	return _c
}

// GetOTP provides a mock function for the type MockIOTPRepo
func (_mock *MockIOTPRepo) GetOTP(context1 context.Context, s string) (string, error) {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for GetOTP")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(context1, s)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(context1, s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIOTPRepo_GetOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOTP'
type MockIOTPRepo_GetOTP_Call struct {
	*mock.Call
}

// GetOTP is a helper method to define mock.On call
//   - context1
//   - s
func (_e *MockIOTPRepo_Expecter) GetOTP(context1 interface{}, s interface{}) *MockIOTPRepo_GetOTP_Call {
	return &MockIOTPRepo_GetOTP_Call{Call: _e.mock.On("GetOTP", context1, s)}
}

func (_c *MockIOTPRepo_GetOTP_Call) Run(run func(context1 context.Context, s string)) *MockIOTPRepo_GetOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockIOTPRepo_GetOTP_Call) Return(s1 string, err error) *MockIOTPRepo_GetOTP_Call {
	_c.Call.Return(s1, err)
	return _c
}

func (_c *MockIOTPRepo_GetOTP_Call) RunAndReturn(run func(context1 context.Context, s string) (string, error)) *MockIOTPRepo_GetOTP_Call {
	_c.Call.Return(run)
	return _c
}

// SaveOTP provides a mock function for the type MockIOTPRepo
func (_mock *MockIOTPRepo) SaveOTP(context1 context.Context, s string, s1 string, duration time.Duration) error {
	ret := _mock.Called(context1, s, s1, duration)

	if len(ret) == 0 {
		panic("no return value specified for SaveOTP")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = returnFunc(context1, s, s1, duration)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIOTPRepo_SaveOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveOTP'
type MockIOTPRepo_SaveOTP_Call struct {
	*mock.Call
}

// SaveOTP is a helper method to define mock.On call
//   - context1
//   - s
//   - s1
//   - duration
func (_e *MockIOTPRepo_Expecter) SaveOTP(context1 interface{}, s interface{}, s1 interface{}, duration interface{}) *MockIOTPRepo_SaveOTP_Call {
	return &MockIOTPRepo_SaveOTP_Call{Call: _e.mock.On("SaveOTP", context1, s, s1, duration)}
}

func (_c *MockIOTPRepo_SaveOTP_Call) Run(run func(context1 context.Context, s string, s1 string, duration time.Duration)) *MockIOTPRepo_SaveOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockIOTPRepo_SaveOTP_Call) Return(err error) *MockIOTPRepo_SaveOTP_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIOTPRepo_SaveOTP_Call) RunAndReturn(run func(context1 context.Context, s string, s1 string, duration time.Duration) error) *MockIOTPRepo_SaveOTP_Call {
	_c.Call.Return(run)
	return _c
}
