all: true
dir: "{{.InterfaceDir}}"
filename: "Mock{{.InterfaceName}}.go"
force-file-write: true
formatter: goimports
log-level: info
structname: "{{.Mock}}{{.InterfaceName}}"
pkgname: "{{.SrcPackageName}}"
recursive: false
require-template-schema-exists: true
template: testify
template-schema: "{{.Template}}.schema.json"
packages:
  nipun.io/otp-service/repo:
    config:
      all: true
